name: Generate Contribution Snake

on:
  schedule:
    - cron: "45 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/github-contribution-grid-snake.svg?palette=github-light
            profile/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update contribution snake"
          add: "profile/*.svg"
